apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
spec:
  replicas: 3
  minReadySeconds: 30
  selector:
    matchLabels:
      app: hello-world-k8s
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hello-world-k8s
    spec:
      containers:
      - name: hello-world-k8s
        image: 10.142.0.5:5000/jenkins-kubernetes:$BUILD_NUMBER
        command: [sh, -c, "sleep 1000"]
        args: [ "while true; do sleep 30; done;" ]
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: registry-secret
---
apiVersion: v1
kind: Service
metadata:
  labels:
  name: hello-world-k8s
spec:
  ports:
  - name: "hello-world-k8s"
    port: 8086
    targetPort: 8080
  selector:
status:
  loadBalancer: {}
